// Builds the 30 mazes of Cheese Chase into web/js/levels.js.
// A maze is a 9x9 grid of crossings, 3 tiles apart, joined by corridors; random corridors are
// closed (mirrored left/right) as long as every crossing keeps at least two ways out (no dead
// ends) and the whole maze stays connected. The cats' house is the middle crossing.
// Run: node tools/gen-levels.mjs
//
// Maze characters (27x27 tiles of 8px):
//   # wall   . crumb   o big cheese   (space) empty path   T tunnel (wraps to the other side)
//   - house door (cats only)   = inside the house
import { writeFileSync } from 'node:fs';

const N = 9, S = 27, C = 4, COUNT = 30;

function rng(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const key = (k, a, b) => k + a + ',' + b;   // H j,i joins (i,j)-(i+1,j); V j,i joins (i,j)-(i,j+1)
const FORCED_ON = ['H3,3', 'H3,4', 'H5,3', 'H5,4', 'V3,3', 'V4,3', 'V3,5', 'V4,5', 'H6,3', 'H6,4'];
const FORCED_OFF = ['H4,3', 'H4,4', 'V3,4', 'V4,4'];

function build(index) {
  const r = rng(index * 4241 + 7);
  const tunnel = index % 3 !== 1;
  const on = new Set();
  for (let j = 0; j < N; j++) for (let i = 0; i < N - 1; i++) on.add(key('H', j, i));
  for (let j = 0; j < N - 1; j++) for (let i = 0; i < N; i++) on.add(key('V', j, i));
  FORCED_OFF.forEach((k) => on.delete(k));

  const edgesOf = (i, j) => {
    const list = [];
    if (i > 0 && on.has(key('H', j, i - 1))) list.push([i - 1, j]);
    if (i < N - 1 && on.has(key('H', j, i))) list.push([i + 1, j]);
    if (j > 0 && on.has(key('V', j - 1, i))) list.push([i, j - 1]);
    if (j < N - 1 && on.has(key('V', j, i))) list.push([i, j + 1]);
    if (tunnel && j === 4 && i === 0) list.push([N - 1, 4]);
    if (tunnel && j === 4 && i === N - 1) list.push([0, 4]);
    return list;
  };
  const ok = () => {
    for (let j = 0; j < N; j++) for (let i = 0; i < N; i++) {
      if (i === C && j === C) continue;
      if (edgesOf(i, j).length < 2) return false;
    }
    const seen = new Set(['0,0']);
    const q = [[0, 0]];
    while (q.length) {
      const [i, j] = q.pop();
      for (const [a, b] of edgesOf(i, j)) {
        if (!seen.has(a + ',' + b)) { seen.add(a + ',' + b); q.push([a, b]); }
      }
    }
    return seen.size === N * N - 1;
  };

  // groups of mirrored edges that may be closed
  const groups = [];
  const done = new Set();
  for (const k of on) {
    if (done.has(k) || FORCED_ON.includes(k)) continue;
    const [, j, i] = /^[HV](\d),(\d)$/.exec(k).map(Number);
    const m = k[0] === 'H' ? key('H', j, N - 2 - i) : key('V', j, N - 1 - i);
    done.add(k); done.add(m);
    groups.push(k === m ? [k] : [k, m]);
  }
  for (let i = groups.length - 1; i > 0; i--) {
    const k = Math.floor(r() * (i + 1));
    [groups[i], groups[k]] = [groups[k], groups[i]];
  }
  const target = Math.round(groups.length * (0.32 + r() * 0.22));
  let removed = 0;
  for (const g of groups) {
    if (removed >= target) break;
    g.forEach((k) => on.delete(k));
    if (ok()) removed++;
    else g.forEach((k) => on.add(k));
  }
  if (!ok()) throw new Error('maze ' + index + ' broken');

  // draw the tiles
  const t = [];
  for (let y = 0; y < S; y++) t.push(new Array(S).fill('#'));
  const P = (n) => 1 + 3 * n;
  for (let j = 0; j < N; j++) for (let i = 0; i < N; i++) if (!(i === C && j === C)) t[P(j)][P(i)] = '.';
  for (const k of on) {
    const [, j, i] = /^[HV](\d),(\d)$/.exec(k).map(Number);
    if (k[0] === 'H') { t[P(j)][P(i) + 1] = '.'; t[P(j)][P(i) + 2] = '.'; }
    else { t[P(j) + 1][P(i)] = '.'; t[P(j) + 2][P(i)] = '.'; }
  }
  // no crumbs round the house
  for (let y = 10; y <= 16; y++) for (let x = 10; x <= 16; x++) if (t[y][x] === '.') t[y][x] = ' ';
  for (let y = 12; y <= 14; y++) for (let x = 12; x <= 14; x++) t[y][x] = '=';
  t[11][13] = '-';
  t[19][13] = ' ';
  if (tunnel) { t[13][0] = 'T'; t[13][S - 1] = 'T'; }
  for (const [x, y] of [[1, 4], [25, 4], [1, 22], [25, 22]]) t[y][x] = 'o';
  return { maze: t.map((row) => row.join('')), tunnel };
}

const levels = [];
for (let i = 0; i < COUNT; i++) levels.push(build(i));
let js = '// Generated by tools/gen-levels.mjs. Do not edit by hand.\n';
js += 'var BC = window.BC || (window.BC = {});\nBC.LEVELS = ' + JSON.stringify(levels) + ';\n';
writeFileSync(new URL('../web/js/levels.js', import.meta.url), js);
console.log(levels[0].maze.join('\n'));
console.log(levels.map((l, i) => (i + 1) + ':' + (l.maze.join('').match(/[.o]/g) || []).length).join(' '));
